#!/usr/bin/env python3
import jira_access
import datetime
import argparse


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '-r',
        '--remote_branch',
        type=str,
        default='',
        help='The name of the remote branch which want to push'
    )

    FLAGS, unparsed = parser.parse_known_args()

    remote_branch = FLAGS.remote_branch

    print(remote_branch)
    if remote_branch == "":
        print("Please let me know which remote branch you want to push")
        exit(-1)


    p = datetime.datetime.now()
    st = jira_access.push_to_gerrit(remote_branch)
    print("Write commit info to jira...")

    print(st)
    dr = jira_access.write_commit_info(jira_access.get_current_branch(), "Fixed.\n" + st)
    print("DONE. ", datetime.datetime.now() - p)
